export const C = {
  bg:       "var(--bg)",
  surface:  "var(--surface)",
  card:     "var(--card)",
  border:   "var(--border)",
  borderHi: "var(--border-hi)",
  coral:    "#E55266",
  magenta:  "#992A67",
  violet:   "#4E0269",
  text:     "var(--text)",
  sub:      "var(--sub)",
  muted:    "var(--muted)",
  dim:      "var(--dim)",
  teal:     "#3ECFB2",
  amber:    "#F0A04B",
  blue:     "#5BADFF",
  red:      "#FF5272",
  grad:     "linear-gradient(135deg,#E55266,#992A67,#4E0269)",
};
